#!/bin/sh

# PROVIDE:  firstboot
# REQUIRE:  FILESYSTEMS
. /etc/rc.subr

name="firstboot" 
rcvar=${name}_enable
start_cmd="firstboot_start"

firstboot_start() {
	/usr/local/bin/freehyve-grow || true
	/usr/local/bin/choose_initial_networking_config.sh
	/usr/sbin/sysrc -f /usr/local/etc/rc.conf firstboot_enable="NO"
}

load_rc_config $name
run_rc_command "$@" 
